//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cBaseQMS.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cBaseDevEntities : DbContext
    {
        public cBaseDevEntities()
            : base("name=cBaseDevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Equation> Equations { get; set; }
        public virtual DbSet<InputField> InputFields { get; set; }
        public virtual DbSet<InputFieldsValue> InputFieldsValues { get; set; }
        public virtual DbSet<LocationAttribte> LocationAttribtes { get; set; }
        public virtual DbSet<PartAttribute> PartAttributes { get; set; }
        public virtual DbSet<TestAttribute> TestAttributes { get; set; }
        public virtual DbSet<TestCalculatedField> TestCalculatedFields { get; set; }
        public virtual DbSet<TestInput> TestInputs { get; set; }
        public virtual DbSet<TestMaster> TestMasters { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<UoM> UoMs { get; set; }
    }
}
