//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cBaseQMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equation
    {
        public int EquationID { get; set; }
        public int TestID { get; set; }
        public string EquationName { get; set; }
        public string Description { get; set; }
        public string Equation1 { get; set; }
        public string Condition { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Test Test { get; set; }
    }
}
