//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cBaseQMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class InputField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InputField()
        {
            this.InputFieldsValues = new HashSet<InputFieldsValue>();
        }
    
        public int InputFieldID { get; set; }
        public int TestInputID { get; set; }
        public string FieldColumnName { get; set; }
        public Nullable<int> FieldRowNo { get; set; }
        public string FieldName { get; set; }
        public Nullable<decimal> CurrentFieldValue { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InputFieldsValue> InputFieldsValues { get; set; }
        public virtual TestInput TestInput { get; set; }
    }
}
