//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cBaseQMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class InputFieldsValue
    {
        public int InputFieldValueID { get; set; }
        public int InputFieldID { get; set; }
        public int TestCycle { get; set; }
        public Nullable<decimal> Value { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual InputField InputField { get; set; }
    }
}
