//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cBaseQMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartAttribute
    {
        public int PartAttrID { get; set; }
        public string PartAttrName { get; set; }
        public int PartMasterID { get; set; }
        public int TestID { get; set; }
        public int InputFieldID { get; set; }
        public decimal MinValue { get; set; }
        public Nullable<decimal> MaxValue { get; set; }
        public Nullable<int> UOMID { get; set; }
        public bool Active { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Test Test { get; set; }
    }
}
