//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cBaseQms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestMasterMapping
    {
        public int TestMasterMapID { get; set; }
        public int TestMasterID { get; set; }
        public int PartMasterID { get; set; }
        public int LocationMasterID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual LocationMaster LocationMaster { get; set; }
        public virtual PartMaster PartMaster { get; set; }
        public virtual TestMaster TestMaster { get; set; }
    }
}
